### ISSUE TITLE
Tracking: Official Babel 7

### ISSUE THREAD

**Issue by wolfy1339** [hellomouse/GNS#35]
- [x] oliviertassinari/babel-plugin-transform-react-remove-prop-types#155
- [ ] airbnb/babel-plugin-dynamic-import-node#64 (Not currently in CRA, CRA's package still uses beta version)
  - [ ] airbnb/babel-preset-airbnb#37
- [x] ~~59naga/babel-plugin-add-module-exports#66~~ Going to be removed in `babel-plugin-dynamic-import-node`
- [x] facebook/create-react-app#4932

**Comment by wolfy1339** [comment]
This doesn't fix the bug. I'll open a new issue for it
